CHART_TEXT_COLOR = "#636363"
CHART_BACKGROUND_COLOR = "white"

BACKGROUND_COLOR = "#F6F6F6"
GENERAL_TEXT_COLOR = "#444444"

SUMMARY_CALORIES_COLOR = "#EA491D"
SUMMARY_EXERCISE_COLOR = "#7ACA21"
SUMMARY_SLEEP_COLOR = "#2651EB"

SUMMARY_WAKE_UP_VARIABILITY_COLOR = '#EBB626'
SUMMARY_FALL_ASLEEP_VARIABILITY_COLOR = '#474F6B'